apiVersion:  apps/v1
kind: Deployment
metadata:
  name: contagem-deployment
spec:
  selector: 
    matchLabels: 
      app: contagem 
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: contagem
    spec:
      containers:
      - name: contagem
        image: meetup.azurecr.io/miltoncamara/aspnetcore2.1_kubernetes:#{Build.BuildId}#
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: contagemregistrykey
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service 
kind: Service
metadata:
  name: contagem-service
  labels:
    version: test
spec:
  selector:
    app: contagem
  ports:
  - port: 80
  type: LoadBalancer
